// controllers/authController.js
const User = require('../models/User');
const generateToken = require('../utils/generateToken'); // You'll create this helper

// @desc    Register a new user
// @route   POST /api/auth/register
// @access  Public
exports.registerUser = async (req, res) => {
  const { username, email, password } = req.body;

  try {
    if (!username || !email || !password) {
        return res.status(400).json({ message: 'Please provide username, email, and password' });
    }

    const userExists = await User.findOne({ $or: [{ email }, { username }] });

    if (userExists) {
      return res.status(400).json({ message: 'User already exists with this email or username' });
    }

    // The password will be hashed and clientSalt generated by the pre-save hook in User.js
    const user = await User.create({
      username,
      email,
      passwordHash: password, // Pass the plain password, it will be hashed by the model
    });

    if (user) {
      res.status(201).json({
        _id: user._id,
        username: user.username,
        email: user.email,
        clientSalt: user.clientSalt, // Send salt for client-side key derivation
        token: generateToken(user._id),
      });
    } else {
      res.status(400).json({ message: 'Invalid user data' });
    }
  } catch (error) {
    console.error("Registration Error:", error);
    res.status(500).json({ message: 'Server error during registration', error: error.message });
  }
};

// @desc    Auth user & get token (Login)
// @route   POST /api/auth/login
// @access  Public
exports.loginUser = async (req, res) => {
  const { emailOrUsername, password } = req.body;

  try {
    if (!emailOrUsername || !password) {
        return res.status(400).json({ message: 'Please provide email/username and password' });
    }
    const user = await User.findOne({
      $or: [{ email: emailOrUsername }, { username: emailOrUsername }],
    });

    if (user && (await user.matchPassword(password))) {
      res.json({
        _id: user._id,
        username: user.username,
        email: user.email,
        clientSalt: user.clientSalt, // Send salt for client-side key derivation
        token: generateToken(user._id),
      });
    } else {
      res.status(401).json({ message: 'Invalid email/username or password' });
    }
  } catch (error) {
    console.error("Login Error:", error);
    res.status(500).json({ message: 'Server error during login', error: error.message });
  }
};

// @desc    Get user profile (example protected route)
// @route   GET /api/auth/me
// @access  Private
exports.getUserProfile = async (req, res) => {
    // req.user is set by the authMiddleware
    const user = await User.findById(req.user.id).select('-passwordHash'); // Exclude passwordHash
    if (user) {
        res.json({
            _id: user._id,
            username: user.username,
            email: user.email,
            clientSalt: user.clientSalt,
        });
    } else {
        res.status(404).json({ message: 'User not found' });
    }
};